---
- hosts: all
  gather_facts: False
  connection: local

  tasks:
  - name: BUILD REMEDIATION CONFIG WITHOUT TAGS
    netdevops.hier_config.remediation:
      hostname: router1.rtr
      running_config: router1-running.conf
      generated_config: router1-generated.conf
      remediation_config: router1-remediation.conf
      os_role: os_iosxr

  - name: BUILD REMEDIATION CONFIG WITH INCLUDE TAGS
    netdevops.hier_config.remediation:
      hostname: router1.rtr
      running_config: router1-running.conf
      generated_config: router1-generated.conf
      remediation_config: router1-remediation-with-include-tags.conf
      os_role: os_iosxr
      include_tags: push

  - name: BUILD REMEDIATION CONFIG WITH EXCLUDE TAGS
    netdevops.hier_config.remediation:
      hostname: router1.rtr
      running_config: router1-running.conf
      generated_config: router1-generated.conf
      remediation_config: router1-remediation-with-exclude-tags.conf
      os_role: os_iosxr
      exclude_tags: ignore

  - name: BUILD REMEDIATION CONFIG WITH INCLUDE AND EXCLUDE TAGS
    netdevops.hier_config.remediation:
      hostname: router1.rtr
      running_config: router1-running.conf
      generated_config: router1-generated.conf
      remediation_config: router1-remediation-with-tags.conf
      os_role: os_iosxr
      exclude_tags: ignore
      include_tags: push
